services:
  hong-kong-transport-data:
    image: ghcr.io/jonafanho/hong-kong-transport-data:latest
    container_name: hong-kong-transport-data
    restart: unless-stopped
    ports:
      - "80:8080"
    volumes:
      - ./data:/data
